### ISSUE TITLE
"Morally Strong" Definition

### ISSUE THREAD

**Issue by tonghaining** [NVlabs/mixedproxy#1]
Hi!  I was wondering if the definition of morally strong in the [alloy code](https://github.com/NVlabs/mixedproxy/blob/main/alloy/ptx.als#L295) is the same as the [formal document](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#morally-strong-operations). Also, it seems that weak operations are being [parsed](https://github.com/NVlabs/mixedproxy/blob/main/src/litmus_parser.py#L68) as relaxed instructions. I think this might affect some test cases involving weak operations. Could you please clarify this? Thanks!

**Comment by daniellustig** [comment]
Thanks for the report @tonghaining!  It should be fixed now.

And yes, the tool's definition of morally strong is intended to match the PTX spec definition.  Do you see a place where you think they differ?

**Comment by tonghaining** [comment]
Thanks for your response @daniellustig !
With setting weak operations' scope to None I think it fully matches the definition now.
