### ISSUE TITLE
Addresses in RF relation

### ISSUE THREAD

**Issue by tonghaining** [NVlabs/mixedproxy#3]
Hi there! I noticed that the Read-From relation only verifies the value and not the address. I'm wondering whether the address checking is just omitted, or it's intended for RF across proxies. Could you clearify this? Thanks in advance!
`//rf`
`fact { rf.~rf in iden }`
`fact { all r: Read |
  some r.~rf => r.value = r.~rf.value else r.value = 0
}`

**Comment by hernanponcedeleon** [comment]
Let me give a concrete example where we find this problematic. In the following litmus, we expect the load to `r0` to always read the initial state and not from the store to `s`
```
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 fence.proxy.texture              ;
 tld.weak %r0, t                  ;
exists
(P0:%r0 != 1)
```
The question is, if the `rf` relation the responsible of not matching the store and the load (because they access different virtual addresses), or some axiom should take care of this. If so, which one?

I would expect that the pair can be in `rf` and then to have some axiom that makes any execution with such `rf` but without having both a `texture` and `surface` fence, to be inconsistent.

**Comment by daniellustig** [comment]
Thanks for the question.  Address checking for `rf` is handled by a different fact:
```
fun com : MemoryOp->MemoryOp { rf + ^co + fr }
fact com_addr { com in same_location_r }
```

Note that defining "same-address" gets tricky when trying to account for virtual aliasing, as the PTX model now does.  So this is specifically "same location", which in PTX terms refers roughly to physical address.  The model accounts for aliasing in the definition of this relation:
```
fun same_location_r : Op->Op { address.aliases.~address }
```
https://docs.nvidia.com/cuda/parallel-thread-execution/#memory-operations

In your example, the `sust` and the `tld` are made via different proxies but aren't properly synchronized, so they form an intra-thread data race.  Therefore, the execution where the `tld` does observe the value written by the `sust` is indeed a possible outcome.

Does that answer your questions?

**Comment by hernanponcedeleon** [comment]
> Thanks for the question. Address checking for `rf` is handled by a different fact:
> 
> ```
> fun com : MemoryOp->MemoryOp { rf + ^co + fr }
> fact com_addr { com in same_location_r }
> ```

I missed this fact. It makes sense.

> In your example, the `sust` and the `tld` are made via different proxies but aren't properly synchronized, so they form an intra-thread data race. Therefore, the execution where the `tld` does observe the value written by the `sust` is indeed a possible outcome.
> 
> Does that answer your questions?

Let me ask this differently to see if I fully understand this. Most memory models do not allow a load to be `fr`-before a store to the same address in the same thread. In the presence of virtual aliasing, this is possible unless the instructions properly synchronize.

Thus, the following would have these expected results
```
Test 1
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 fence.proxy.texture              ;
 tld.weak %r0, t                  ;
exists
(P0:%r0 != 1)
```
Allowed.
```
Test 2
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 fence.proxy.texture              ;
 fence.proxy.surface              ;
 tld.weak %r0, t                  ;
exists
(P0:%r0 != 1)
```
Not allowed.
```
Test 3
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 fence.proxy.texture              ;
 tld.weak %r0, x                  ;
exists
(P0:%r0 != 1)
```
Not allowed.
```
Test 4
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 fence.proxy.surface              ;
 tld.weak %r0, x                  ;
exists
(P0:%r0 != 1)
```
Allowed.
```
Test 5
{
x = 0;
t @ texture aliases x;
s @ surface aliases x;
P0:%r0=0;
}
 P0@cta 0,gpu 0                   ;
 sust.weak s, 1                   ;
 tld.weak %r0, x                  ;
exists
(P0:%r0 != 1)
```
Allowed.

**Comment by daniellustig** [comment]
All of those test outcomes are allowed.  The test 2 outcome is allowed because the proxy fences are in the wrong order.  The test 3 outcome is allowed because there is no surface proxy fence at all.  In all cases, the texture load can therefore get ahead of the surface store, through one or more of the mechanisms described in the paper.

**Comment by hernanponcedeleon** [comment]
I thought that the events were getting the "proxy tag" depending on the kind of address they accessed. However, I just noted the prefixes `su` and `t` in the surface store and the texture load. With that in mind, does it make sense to have `tld.weak %r0, x` (a texture access to a generic address), or should this be forbidden?

I am surprised that the order of fences in Test 2 has an effect. I would expect `fence.proxy.texture` to forbid to pop-up the load (similar and acquire fence) and `fence.proxy.surface` to forbid to delay the store (similar to a release). Can you explain what is the rationale about the order being important?

**Comment by daniellustig** [comment]
Indeed, the instruction is what is relevant.  PTX generally only allows passing [pointer to] .texref to texture instructions, and [pointer to] .surfref for surface instructions.  So some of the combinations you're brainstorming about simply aren't supported in practice, even though one could ponder what they'd mean abstractly within the memory model.

Re test 2, in the type of microarchitecture described in the paper, here is one possible execution that shows why fence ordering matters:

```
 sust.weak s, 1                   ; // push to writeback surface cache; don't write back to memory yet
 fence.proxy.texture              ; // invalidate the texture cache (no texture stores to push)
                                    // prefetch stale copy of x/s/t from memory into the texture cache
 fence.proxy.surface              ; // push dirty data from surface cache to memory (and invalidate surface cache)
 tld.weak %r0, t                  ; // load stale data from texture cache
```

**Comment by hernanponcedeleon** [comment]
Ok. Now it all makes sense to me. Thanks @daniellustig for all the explanations. Unless @tonghaining has more questions, I think this issue can be closed

**Comment by tonghaining** [comment]
same here, thanks @daniellustig
