### ISSUE TITLE
Adding po to cause_base may affect pre-existing memory model without proxies

### ISSUE THREAD

**Issue by tonghaining** [NVlabs/mixedproxy#4]
Hi, we encountered a potential issue while examining the update that adding the `program-order` relation into the `base-causality-order` relation in the PTX memory model. It appears that the update has an impact on the pre-existing memory model without proxies, which is in contrast to the claim made in the ISCA'22 paper. To illustrate this concern, we have prepared a litmus test counter example:
```
.global x;
.global f1;
.global f2;

d0.b0.t0 {
  st.weak [x], 1;
  st.release.sys [f1], 1;
}

d0.b1.t0 {
  st.release.gpu [x], 2;
  ld.weak r0, [x];
  st.release.sys [f2], 1;
}
d0.b2.t0 {
  ld.acquire.sys r1, [f2];
  ld.acquire.sys r2, [f2];
  ld.weak r3, [x];
}

permit (r0 == 0 && r1 == 1 && r2 == 1 && r3 == 2) as my_test;
```

Could you take a look into this matter? thanks!

**Comment by daniellustig** [comment]
That is a big litmus test, and I'm not 100% sure what it's trying to show...  Is it the minimal counterexample?  Did you modify the Alloy model to capture the "before" vs. "after"?

For one thing, the thread 0 store to `x` and the thread 1 accesses of `x` are racy, so it's hard to draw a lot of intuition about what synchronization pattern this is supposed to represent.

For another, `P1:r0==0` should be illegal both before and after, since it's a CoWR violation, independent of what the other threads do.  Does the "before" model somehow permit it?  If so, then I think the "before" model might just have a bug...

**Comment by hernanponcedeleon** [comment]
This was our original example
```
PTX Test1
{
x=0;
P1:r1=0;
}
 P0@cta 0,gpu 0         | P1@cta 1,gpu 0          ;
 st.weak x, 1           | st.release.gpu x, 2     ;
                        | ld.weak r1, x           ;
exists
(x == 2 /\ P1:r1 == 0)
```
We added the extra thread and the flag variables `f1,f2` to cope with the fact that the alloy tool does not allow to refer to locations in the final assertion.

The problem might indeed be related to the fact that the code has a data race, because we still get different results in this test
```
PTX Test2
{
x=0;
P1:r1=0;
}
 P0@cta 0,gpu 0         | P1@cta 1,gpu 0          ;
 st.release.gpu x, 1    | st.release.gpu x, 2     ;
                        | ld.weak r1, x           ;
exists
(x == 2 /\ P1:r1 == 0)
```  
but not with this one
```
PTX Test3
{
x=0;
P1:r1=0;
}
 P0@cta 0,gpu 0         | P1@cta 1,gpu 0          ;
 st.release.gpu x, 1    | st.release.gpu x, 2     ;
                        | ld.acquire.gpu r1, x    ;
exists
(x == 2 /\ P1:r1 == 0)
```  
Is there a formal way to add the data race definition to the model, like [in lkmm](https://github.com/torvalds/linux/blob/master/tools/memory-model/linux-kernel.cat#L216)?

**Comment by daniellustig** [comment]
OK, the use of the flags makes sense now, thank you.

However, I still don't follow what you mean by "get different results".  Can you please elaborate?  AFAICT the proposed outcome should still be disallowed in all cases, i.e., there should be no valid execution (in a proxy-less model) where a load is `fr`-before an earlier store in the same thread.

**Comment by tonghaining** [comment]
We update the [cause_base](https://github.com/NVlabs/mixedproxy/blob/main/alloy/ptx.als#L190) to be:
```
fun cause_base : Op->Op {
 *po.^((sc + sync).*po)
}
```
which we think is consistent with the [proxy-less model](https://github.com/NVlabs/ptxmemorymodel/blob/master/ptx.als#L95) way. And below is the whole output of the test with this change:
```
// NVLitmus is a research prototype, and comes with no guarantees of completeness, correctness, or authoritativeness.  Please see https://github.com/NVlabs/mixedproxy for more information.
Test:
.global x;
.global f1;
.global f2;

d0.b0.t0 {
  st.release.sys [x], 1;
  st.release.sys [f1], 1;
}

d0.b1.t0 {
  st.release.gpu [x], 2;
  ld.acquire.sys r0, [x];
  st.release.sys [f2], 1;
}
d0.b2.t0 {
  ld.acquire.sys r1, [f2];
  ld.acquire.sys r2, [f2];
  ld.acquire.sys r3, [x];
}

permit (r0 == 0 && r1 == 1 && r2 == 1 && r3 == 2) as my_test;

Launching Alloy...
my_test: SAT, outcome permitted, matches expectation
```
As a comparison, in the ptx-proxy with cause_base containing the `^po` which is
```
fun cause_base : Op->Op {
  ^po + *po.^((sc + sync).*po)
}
```
The output we got from the same test is:
```
// NVLitmus is a research prototype, and comes with no guarantees of completeness, correctness, or authoritativeness.  Please see https://github.com/NVlabs/mixedproxy for more information.
Test:
.global x;
.global f1;
.global f2;

d0.b0.t0 {
  st.release.sys [x], 1;
  st.release.sys [f1], 1;
}

d0.b1.t0 {
  st.release.gpu [x], 2;
  ld.acquire.sys r0, [x];
  st.release.sys [f2], 1;
}
d0.b2.t0 {
  ld.acquire.sys r1, [f2];
  ld.acquire.sys r2, [f2];
  ld.acquire.sys r3, [x];
}

permit (r0 == 0 && r1 == 1 && r2 == 1 && r3 == 2) as my_test;

Launching Alloy...
my_test: UNSAT, outcome not permitted, breaks expectation
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Alloy exited with code 10
// Alloy exited with non-zero return code
```

**Comment by hernanponcedeleon** [comment]
Just to avoid confusion: @tonghaining is showing the result of Test3. Hopefully, this should be enough to understand why the alloy model allows this behavior. 

As I mentioned above, our tool+models says this behavior is not allowed when there are not weak accesses. The difference between the tools is probably due to some other small changes we did to our models to follow closer the documentation.

**Comment by hernanponcedeleon** [comment]
We found the reason why both tools return different results on Test3: the original PTX model has this axiom
```
acyclic ((morally-strong & (rf | co | fr)) | po-loc) as axiom-ScPerLocation
```
which is not part of the model in this repo (but we have it in our proxy-less model). Thus if we want to use the tool to reason about the old model, we need to add that axiom.

Is it the case that the axiom becomes trivially satisfied by adding `po` to `cause_base` and thus not included in the proxy model?

However, the initial issue that the claim 

> "The only change required was to add program order to the list below. This change by itself has no effect in the pre-existing memory
 model without proxies"

might not hold, still remains (as witnessed by Test1 and Test2).

**Comment by hernanponcedeleon** [comment]
The litmus test we showed actually had a typo (the last thread was reading twice the `f2` flag). Sorry for the spam.

We did some more testing and ATM we are not aware of any litmus test showing differences between both models, so this issue can be closed.

**Comment by daniellustig** [comment]
Thanks, feel free to reopen or create a new issue if you do find a test that shows the difference.

**Comment by hernanponcedeleon** [comment]
@daniellustig I think we finally found an example showing a difference between v7.5 and v6.0. 

The following test is a snippet of the producer-consumer barrier in the [cutlass library](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/arch/barrier.h), I just had to replace a `sync_barrier` with a `rel-acq` which contributes equally to `sw`.

With the model in this repo, the assertion fails
```
.global x;
.global y;
.global f;
.global g;

d0.b0.t0 {
  ld.acquire.gpu r1, [f];
  st.weak [x], 1;
  fence.acq_rel.gpu;
  st.relaxed.gpu [g], 1;
}

d0.b1.t0 {
  st.relaxed.gpu [f], 1;
  ld.acquire.gpu r2, [g];
  st.release.gpu [y], 1;
}

d0.b1.t1 {
  ld.acquire.gpu r3, [y];
  ld.weak r4, [x];
}

assert (r1 != 1 || r2 != 1 || r3 != 0 || r4 != 1) as diff;
```
Here is the execution graph showing the violation

![Diff-v6 0-v7 5](https://github.com/NVlabs/mixedproxy/assets/11671435/2925ec7e-f03d-4225-9b47-79c9b3ef0a95)

I will explain how `E2 -cause-> E13` which makes this execution violate the causality axiom of v6.0.
E3-E4 form a release pattern. E8 alone forms an acquire pattern. Thus, `E3 -sw-> E8`.
Similarly, we have `E9 -sw-> E12` (this is a `sync_bar` in cutlass).
The chain `E2 -po-> E3 -sw-> E8 -po->E9 -sw-> E12 -po-> E13` is a `cause` edge.

**Comment by daniellustig** [comment]
@hernanponcedeleon thanks for the report.  The cycle looks like a pretty standard ISA2 litmus test, and so the outcome should be forbidden under both models.  The accesses to `f` appear to be extraneous.  Am I misinterpreting anything there?  Are you suggesting that the new model considers this a permitted outcome?  What part of the wording would suggest that?

**Comment by hernanponcedeleon** [comment]
@daniellustig I can even show the problem on a simple MP test.
While this version returns the correct result
```
Test:
.global x;
.global g;

d0.b0.t0 {
  st.weak [x], 1;
  st.release.gpu [g], 1;
}

d0.b1.t0 {
  ld.acquire.gpu r2, [g];
  ld.weak r4, [x];
}

assert (r2 != 1 || r4 == 1) as diff;
Launching Alloy...
diff: UNSAT, assertion confirmed, matches expectation
```

this one does not
```
Test:
.global x;
.global g;

d0.b0.t0 {
  st.weak [x], 1;
  fence.acq_rel.gpu;
  st.relaxed.gpu [g], 1;
}

d0.b1.t0 {
  ld.acquire.gpu r2, [g];
  ld.weak r4, [x];
}

assert (r2 != 1 || r4 == 1) as diff;
Launching Alloy...
diff: SAT, assertion violated, breaks expectation
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        value={i3$0->1, i4$0->0, i0$0->1, i2$0->1}
Alloy exited with code 10
// Alloy exited with non-zero return code
```

I think @tonghaining found the reason. The notion of `morally-strong` in v7.5 requires both operations to be on the same proxy, and it seems that this is failing for the fence. In the violation witness from my previous msg, we do have the release-acquire pattern between E3 and E8, but they are not morally strong and thus they do not contribute to `sw`.  

In the alloy model, I don't see anything about fences having / being part of the same-proxy relation.

**Comment by hernanponcedeleon** [comment]
@daniellustig I took a closer look to the wording of the ISA and [this section](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#causality) says the following about the MP below
```
T1
W1: st.global.u32 [data], 1; 
F1: fence.sys; 
W2: st.global.relaxed.sys.u32 [flag], 1; 

T2
R1: ld.global.relaxed.sys.u32 %r0, [flag]; 
F2: fence.sys; 
R2: ld.global.u32 %r1, [data];
```
> Thread T1 first writes to a data variable and then to a flag variable while a second thread T2 first reads from the flag variable and then from the data variable. The operations on the flag are morally strong and the memory operations in each thread are separated by a fence, and these fences are morally strong.

However, the [definition of morally strong](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#morally-strong-operations) clearly states (point 2) that "Both operations are performed via the same proxy" and I could not find anything in the wording saying anything about normal fence operations (i.e., not `fence.proxy`) and proxies.

**Comment by daniellustig** [comment]
OK I see the issue now, thanks for clarifying.

Our unambiguous intention is for the patterns in question to establish synchronization, just as they did in the original model, and for normal fences to participate in the definition of moral strength just as they did before.  The spec wording may be a little ambiguous about this, and/or the Alloy model might have a bug as it relates to this pattern, but the solution will be to fix those typos to make this work again.

**Comment by hernanponcedeleon** [comment]
I agree that making the fences part of the morally-strong definition (not only F * F, but also F * strongMem and strongMem * F) should fix the problem.

There are a few alternatives to make this. I think any of these would work, but none look to clean to me
-  (F * F | F * strongMem | strongMem * F) subsetof proxy // This sounds kind of artifitial
- new-morally-strong = old-morally-strong | F * F | F * strongMem | strongMem * F // Adding a large disjuction to a definition that is a large conjuction doesn't seem to clean either

**Comment by hernanponcedeleon** [comment]
@daniellustig another (cleaner IMO) solution is to tag non-proxy fences by `GenericProxy`. It definitely solves this problem, and hopefully it does not introduce others.

However, this change would break [this test](https://github.com/NVlabs/mixedproxy/blob/main/tests/Release_acquire_pattern.test) which @tonghaining and I added a while back. At that point, our claim was that the outcome was observable because 
> "the first operation of the release pattern and the last operation of the acquire pattern should be morally strong to make the two patterns synchronized" 

and we believed the release store and the fence were not morally strong. However, I am pretty sure the outcome is not allowed by v6.0 and according to your last msg, I should neither be allowed by v7.5.
